[package]
name = "scrub"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "scrub"
path = "src/main.rs"

[dependencies]
clap  = { version = "4", features = ["derive"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
toml  = "0.8"
dirs  = "5"

[profile.release]
strip     = true
opt-level = 3
